### ISSUE TITLE
Building issue in a cluster

### ISSUE THREAD

**Issue by sogoogos** [OPM/opm-common#338] opened 2018-03-02 10:06 UTC
Hello, I had the following problem when I was trying to build opm-common in a cluster Stampede2 (https://www.tacc.utexas.edu/systems/stampede2).
I was able to build all the modules (dune-common dune-istl dune-geometry dune-grid libecl opm-common opm-parser opm-grid opm-material opm-output ewoms opm-simulators) in my local macbook in the same way. However, it did not somehow work in the cluster with gcc compiler. Can you tell why this happened? It looks like a Boost issue.  I tried both Boost already installed in the system and the one I manually installed, but both of them did not work. 

------------------
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /bin/cc
-- Check for working C compiler: /bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /bin/c++
-- Check for working CXX compiler: /bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- CMake version: 2.8.12.2
-- Linux distribution: CentOS Linux 7 (Core)
-- Target architecture: x86_64
-- Found Git: /opt/apps/git/2.9.0/bin/git (found version "2.9.0")
-- Source code repository: git 8ab7beb
-- GNU C++ compiler version: 4.8.5
-- Linker: ld 2.25.1-32.base.el7_4.2
-- Checking to see if CXX compiler accepts flag -Wl,--enable-new-dtags
-- Checking to see if CXX compiler accepts flag -Wl,--enable-new-dtags - yes
-- Precompiled headers: disabled
-- Build type: Release
-- Checking to see if CXX compiler accepts flag -mtune=native
-- Checking to see if CXX compiler accepts flag -mtune=native - yes
-- All warnings enabled: -Wall
-- OpenMP: disabled
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Checking to see if CXX compiler accepts flag -pthread
-- Checking to see if CXX compiler accepts flag -pthread - yes
-- Could NOT find CppCheck (missing: CPPCHECK_PROGRAM)
-- Disabling clang-check as CMAKE_EXPORT_COMPILE_COMMANDS is not enabled
-- Performing Test HAVE_C99
-- Performing Test HAVE_C99 - Success
-- Found C99: -std=c99
-- Checking to see if CXX compiler accepts flag -std=c++14
-- Checking to see if CXX compiler accepts flag -std=c++14 - no
-- Checking to see if CXX compiler accepts flag -std=c++11
-- Checking to see if CXX compiler accepts flag -std=c++11 - yes
-- Performing Test HAVE_FINAL
-- Performing Test HAVE_FINAL - Success
-- Performing Test HAVE_TYPE_TRAITS
-- Performing Test HAVE_TYPE_TRAITS - Success
-- Performing Test HAVE_SHARED_PTR
-- Performing Test HAVE_SHARED_PTR - Success
-- Performing Test HAVE_UNIQUE_PTR
-- Performing Test HAVE_UNIQUE_PTR - Success
-- Performing Test HAVE_NULLPTR
-- Performing Test HAVE_NULLPTR - Success
-- Performing Test HAVE_CONSTEXPR
-- Performing Test HAVE_CONSTEXPR - Success
-- Performing Test HAVE_ARRAY
-- Performing Test HAVE_ARRAY - Success
-- Performing Test HAVE_INTEGRAL_CONSTANT
-- Performing Test HAVE_INTEGRAL_CONSTANT - Success
-- Looking for C++ include tuple
-- Looking for C++ include tuple - found
-- Looking for C++ include tr1/tuple
-- Looking for C++ include tr1/tuple - found
-- Performing Test HAVE_ATTRIBUTE_ALWAYS_INLINE
-- Performing Test HAVE_ATTRIBUTE_ALWAYS_INLINE - Success
-- Performing Test HAS_ATTRIBUTE_UNUSED
-- Performing Test HAS_ATTRIBUTE_UNUSED - Success
-- Performing Test HAS_ATTRIBUTE_DEPRECATED
-- Performing Test HAS_ATTRIBUTE_DEPRECATED - Success
-- Performing Test HAS_ATTRIBUTE_DEPRECATED_MSG
-- Performing Test HAS_ATTRIBUTE_DEPRECATED_MSG - Success
-- Performing Test HAVE_STATIC_ASSERT
-- Performing Test HAVE_STATIC_ASSERT - Success
-- Performing Test HAVE_AUTO
-- Performing Test HAVE_AUTO - Success
-- Performing Test HAVE_VARIADIC_TEMPLATES
-- Performing Test HAVE_VARIADIC_TEMPLATES - Success
-- Performing Test HAVE_VARIADIC_CONSTRUCTOR_SFINAE
-- Performing Test HAVE_VARIADIC_CONSTRUCTOR_SFINAE - Success
-- Performing Test HAVE_RVALUE_REFERENCES
-- Performing Test HAVE_RVALUE_REFERENCES - Success
-- Looking for C++ include tr1/type_traits
-- Looking for C++ include tr1/type_traits - found
-- Boost version: 1.64.0
-- Found the following Boost libraries:
-- system
-- unit_test_framework
-- Generating debug symbols: -ggdb3
-- Looking for strip utility
-- Looking for strip utility - found
-- Performing Test HAVE_DYNAMIC_BOOST_TEST
-- Performing Test HAVE_DYNAMIC_BOOST_TEST - Failed
-- Writing config file "/work/02552/sogoogos/rmine/OPM_20180221/opm-common/cmake-build-release/config.h"...
-- This build defaults to installing in /work/02552/sogoogos/rmine/foo_20180221
-- Found Doxygen: /bin/doxygen (found version "1.8.5")
-- Writing version information to local header project-version.h
-- Configuring done
-- Generating done
-- Build files have been written to: /work/02552/sogoogos/rmine/OPM_20180221/opm-common/cmake-build-release

-------------------------------
....
Linking CXX static library lib/libopmcommon.a
[ 64%] Built target opmcommon
Scanning dependencies of target test_OpmLog
Scanning dependencies of target test_SimulationDataContainer
[ 72%] [ 72%] Building CXX object CMakeFiles/test_SimulationDataContainer.dir/tests/test_SimulationDataContainer.cpp.o
Building CXX object CMakeFiles/test_OpmLog.dir/tests/test_OpmLog.cpp.o
Linking CXX executable bin/test_SimulationDataContainer
/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/crt1.o: In function _start': (.text+0x20): undefined reference tomain'
CMakeFiles/test_SimulationDataContainer.dir/tests/test_SimulationDataContainer.cpp.o: In function boost::unit_test::make_test_case(boost::function<void ()> const&, boost::unit_test::basic_cstring<char const>, boost::unit_test::basic_cstring<char const>, unsigned long)': test_SimulationDataContainer.cpp:(.text._ZN5boost9unit_test14make_test_caseERKNS_8functionIFvvEEENS0_13basic_cstringIKcEES8_m[_ZN5boost9unit_test14make_test_caseERKNS_8functionIFvvEEENS0_13basic_cstringIKcEES8_m]+0x20): undefined reference toboost::unit_test::ut_detail::normalize_test_case_name(boost::unit_test::basic_cstring)'
/opt/apps/gcc7_1/boost/1.64/lib/libboost_timer.so.1.64.0: undefined reference to VTT for std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21' /opt/apps/gcc7_1/boost/1.64/lib/libboost_system.so: undefined reference tostd::__cxx11::basic_string<char, std::char_traits, std::allocator >::_M_create(unsigned long&, unsigned long)@GLIBCXX_3.4.21'
/opt/apps/gcc7_1/boost/1.64/lib/libboost_unit_test_framework.so: undefined reference to std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator=(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&)@GLIBCXX_3.4.21' /opt/apps/gcc7_1/boost/1.64/lib/libboost_unit_test_framework.so: undefined reference tostd::__cxx11::basic_stringbuf<char, std::char_traits, std::allocator >::str() const@GLIBCXX_3.4.21'
/opt/apps/gcc7_1/boost/1.64/lib/libboost_unit_test_framework.so: undefined reference to std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream(std::_Ios_Openmode)@GLIBCXX_3.4.21' /opt/apps/gcc7_1/boost/1.64/lib/libboost_unit_test_framework.so: undefined reference tostd::__cxx11::basic_string<char, std::char_traits, std::allocator >::_M_append(char const*, unsigned long)@GLIBCXX_3.4.21'
/opt/apps/gcc7_1/boost/1.64/lib/libboost_unit_test_framework.so: undefined reference to std::runtime_error::runtime_error(std::runtime_error const&)@GLIBCXX_3.4.21' /opt/apps/gcc7_1/boost/1.64/lib/libboost_unit_test_framework.so: undefined reference tostd::__cxx11::basic_string<char, std::char_traits, std::allocator >::_M_replace(unsigned long, unsigned long, char const*, unsigned long)@GLIBCXX_3.4.21'
/opt/apps/gcc7_1/boost/1.64/lib/libboost_unit_test_framework.so: undefined reference to std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct(unsigned long, char)@GLIBCXX_3.4.21' /opt/apps/gcc7_1/boost/1.64/lib/libboost_unit_test_framework.so: undefined reference tovtable for std::__cxx11::basic_stringbuf<char, std::char_traits, std::allocator >@GLIBCXX_3.4.21'
/opt/apps/gcc7_1/boost/1.64/lib/libboost_timer.so.1.64.0: undefined reference to vtable for std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21' /opt/apps/gcc7_1/boost/1.64/lib/libboost_unit_test_framework.so: undefined reference tostd::__cxx11::basic_string<char, std::char_traits, std::allocator >::_M_assign(std::__cxx11::basic_string<char, std::char_traits, std::allocator > const&)@GLIBCXX_3.4.21'
/opt/apps/gcc7_1/boost/1.64/lib/libboost_unit_test_framework.so: undefined reference to std::__cxx11::basic_istringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_istringstream()@GLIBCXX_3.4.21' /opt/apps/gcc7_1/boost/1.64/lib/libboost_unit_test_framework.so: undefined reference tovtable for std::__cxx11::basic_istringstream<char, std::char_traits, std::allocator >@GLIBCXX_3.4.21'
/opt/apps/gcc7_1/boost/1.64/lib/libboost_unit_test_framework.so: undefined reference to std::runtime_error::runtime_error(char const*)@GLIBCXX_3.4.21' /opt/apps/gcc7_1/boost/1.64/lib/libboost_unit_test_framework.so: undefined reference totypeinfo for std::__cxx11::basic_ostringstream<char, std::char_traits, std::allocator >@GLIBCXX_3.4.21'
/opt/apps/gcc7_1/boost/1.64/lib/libboost_unit_test_framework.so: undefined reference to vtable for std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21' /opt/apps/gcc7_1/boost/1.64/lib/libboost_unit_test_framework.so: undefined reference tostd::__cxx11::basic_string<char, std::char_traits, std::allocator >::reserve(unsigned long)@GLIBCXX_3.4.21'
/opt/apps/gcc7_1/boost/1.64/lib/libboost_unit_test_framework.so: undefined reference to VTT for std::__cxx11::basic_istringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21' /opt/apps/gcc7_1/boost/1.64/lib/libboost_unit_test_framework.so: undefined reference tostd::__throw_out_of_range_fmt(char const*, ...)@GLIBCXX_3.4.20'
/opt/apps/gcc7_1/boost/1.64/lib/libboost_unit_test_framework.so: undefined reference to std::runtime_error::runtime_error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21' /opt/apps/gcc7_1/boost/1.64/lib/libboost_unit_test_framework.so: undefined reference tostd::__cxx11::basic_string<char, std::char_traits, std::allocator >::rfind(char, unsigned long) const@GLIBCXX_3.4.21'
/opt/apps/gcc7_1/boost/1.64/lib/libboost_unit_test_framework.so: undefined reference to std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::_M_sync(char*, unsigned long, unsigned long)@GLIBCXX_3.4.21' /opt/apps/gcc7_1/boost/1.64/lib/libboost_unit_test_framework.so: undefined reference tostd::__cxx11::basic_ostringstream<char, std::char_traits, std::allocator >::~basic_ostringstream()@GLIBCXX_3.4.21'
/opt/apps/gcc7_1/boost/1.64/lib/libboost_unit_test_framework.so: undefined reference to std::runtime_error::runtime_error(char const*)@GLIBCXX_3.4.21' /opt/apps/gcc7_1/boost/1.64/lib/libboost_unit_test_framework.so: undefined reference tostd::__cxx11::basic_ostringstream<char, std::char_traits, std::allocator >::basic_ostringstream(std::_Ios_Openmode)@GLIBCXX_3.4.21'
/opt/apps/gcc7_1/boost/1.64/lib/libboost_system.so: undefined reference to std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()@GLIBCXX_3.4.21' /opt/apps/gcc7_1/boost/1.64/lib/libboost_unit_test_framework.so: undefined reference tostd::__cxx11::basic_string<char, std::char_traits, std::allocator >::append(char const*)@GLIBCXX_3.4.21'
/opt/apps/gcc7_1/boost/1.64/lib/libboost_unit_test_framework.so: undefined reference to std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_ostringstream()@GLIBCXX_3.4.21' /opt/apps/gcc7_1/boost/1.64/lib/libboost_unit_test_framework.so: undefined reference toVTT for std::__cxx11::basic_ostringstream<char, std::char_traits, std::allocator >@GLIBCXX_3.4.21'
/opt/apps/gcc7_1/boost/1.64/lib/libboost_system.so: undefined reference to operator delete(void*, unsigned long)@CXXABI_1.3.9' /opt/apps/gcc7_1/boost/1.64/lib/libboost_unit_test_framework.so: undefined reference tostd::__cxx11::basic_string<char, std::char_traits, std::allocator >::find(char const*, unsigned long, unsigned long) const@GLIBCXX_3.4.21'
/opt/apps/gcc7_1/boost/1.64/lib/libboost_unit_test_framework.so: undefined reference to std::__cxx11::basic_istringstream<char, std::char_traits<char>, std::allocator<char> >::basic_istringstream(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::_Ios_Openmode)@GLIBCXX_3.4.21' /opt/apps/gcc7_1/boost/1.64/lib/libboost_unit_test_framework.so: undefined reference tostd::__cxx11::basic_stringstream<char, std::char_traits, std::allocator >::~basic_stringstream()@GLIBCXX_3.4.21'
/opt/apps/gcc7_1/boost/1.64/lib/libboost_unit_test_framework.so: undefined reference to std::runtime_error::runtime_error(std::runtime_error const&)@GLIBCXX_3.4.21' collect2: error: ld returned 1 exit status make[2]: *** [bin/test_SimulationDataContainer] Error 1 make[1]: *** [CMakeFiles/test_SimulationDataContainer.dir/all] Error 2 make[1]: *** Waiting for unfinished jobs.... Linking CXX executable bin/test_OpmLog /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/crt1.o: In function_start':
(.text+0x20): undefined reference to main' CMakeFiles/test_OpmLog.dir/tests/test_OpmLog.cpp.o: In functionboost::unit_test::make_test_case(boost::function<void ()> const&, boost::unit_test::basic_cstring, boost::unit_test::basic_cstring, unsigned long)':
test_OpmLog.cpp:(.text._ZN5boost9unit_test14make_test_caseERKNS_8functionIFvvEEENS0_13basic_cstringIKcEES8_m[_ZN5boost9unit_test14make_test_caseERKNS_8functionIFvvEEENS0_13basic_cstringIKcEES8_m]+0x20): undefined reference to boost::unit_test::ut_detail::normalize_test_case_name(boost::unit_test::basic_cstring<char const>)' /opt/apps/gcc7_1/boost/1.64/lib/libboost_timer.so.1.64.0: undefined reference toVTT for std::__cxx11::basic_stringstream<char, std::char_traits, std::allocator >@GLIBCXX_3.4.21'
/opt/apps/gcc7_1/boost/1.64/lib/libboost_system.so: undefined reference to std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)@GLIBCXX_3.4.21' /opt/apps/gcc7_1/boost/1.64/lib/libboost_unit_test_framework.so: undefined reference tostd::__cxx11::basic_string<char, std::char_traits, std::allocator >::operator=(std::__cxx11::basic_string<char, std::char_traits, std::allocator >&&)@GLIBCXX_3.4.21'
/opt/apps/gcc7_1/boost/1.64/lib/libboost_unit_test_framework.so: undefined reference to std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::str() const@GLIBCXX_3.4.21' /opt/apps/gcc7_1/boost/1.64/lib/libboost_unit_test_framework.so: undefined reference tostd::__cxx11::basic_stringstream<char, std::char_traits, std::allocator >::basic_stringstream(std::_Ios_Openmode)@GLIBCXX_3.4.21'
/opt/apps/gcc7_1/boost/1.64/lib/libboost_unit_test_framework.so: undefined reference to std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_append(char const*, unsigned long)@GLIBCXX_3.4.21' /opt/apps/gcc7_1/boost/1.64/lib/libboost_unit_test_framework.so: undefined reference tostd::runtime_error::runtime_error(std::runtime_error const&)@GLIBCXX_3.4.21'
/opt/apps/gcc7_1/boost/1.64/lib/libboost_unit_test_framework.so: undefined reference to std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace(unsigned long, unsigned long, char const*, unsigned long)@GLIBCXX_3.4.21' /opt/apps/gcc7_1/boost/1.64/lib/libboost_unit_test_framework.so: undefined reference tostd::__cxx11::basic_string<char, std::char_traits, std::allocator >::_M_construct(unsigned long, char)@GLIBCXX_3.4.21'
/opt/apps/gcc7_1/boost/1.64/lib/libboost_unit_test_framework.so: undefined reference to vtable for std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21' /opt/apps/gcc7_1/boost/1.64/lib/libboost_timer.so.1.64.0: undefined reference tovtable for std::__cxx11::basic_stringstream<char, std::char_traits, std::allocator >@GLIBCXX_3.4.21'
/opt/apps/gcc7_1/boost/1.64/lib/libboost_unit_test_framework.so: undefined reference to std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21' /opt/apps/gcc7_1/boost/1.64/lib/libboost_unit_test_framework.so: undefined reference tostd::__cxx11::basic_istringstream<char, std::char_traits, std::allocator >::~basic_istringstream()@GLIBCXX_3.4.21'
/opt/apps/gcc7_1/boost/1.64/lib/libboost_unit_test_framework.so: undefined reference to vtable for std::__cxx11::basic_istringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21' /opt/apps/gcc7_1/boost/1.64/lib/libboost_unit_test_framework.so: undefined reference tostd::runtime_error::runtime_error(char const*)@GLIBCXX_3.4.21'
/opt/apps/gcc7_1/boost/1.64/lib/libboost_unit_test_framework.so: undefined reference to typeinfo for std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21' /opt/apps/gcc7_1/boost/1.64/lib/libboost_unit_test_framework.so: undefined reference tovtable for std::__cxx11::basic_ostringstream<char, std::char_traits, std::allocator >@GLIBCXX_3.4.21'
/opt/apps/gcc7_1/boost/1.64/lib/libboost_unit_test_framework.so: undefined reference to std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::reserve(unsigned long)@GLIBCXX_3.4.21' /opt/apps/gcc7_1/boost/1.64/lib/libboost_unit_test_framework.so: undefined reference toVTT for std::__cxx11::basic_istringstream<char, std::char_traits, std::allocator >@GLIBCXX_3.4.21'
/opt/apps/gcc7_1/boost/1.64/lib/libboost_unit_test_framework.so: undefined reference to std::__throw_out_of_range_fmt(char const*, ...)@GLIBCXX_3.4.20' /opt/apps/gcc7_1/boost/1.64/lib/libboost_unit_test_framework.so: undefined reference tostd::runtime_error::runtime_error(std::__cxx11::basic_string<char, std::char_traits, std::allocator > const&)@GLIBCXX_3.4.21'
/opt/apps/gcc7_1/boost/1.64/lib/libboost_unit_test_framework.so: undefined reference to std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::rfind(char, unsigned long) const@GLIBCXX_3.4.21' /opt/apps/gcc7_1/boost/1.64/lib/libboost_unit_test_framework.so: undefined reference tostd::__cxx11::basic_stringbuf<char, std::char_traits, std::allocator >::_M_sync(char*, unsigned long, unsigned long)@GLIBCXX_3.4.21'
/opt/apps/gcc7_1/boost/1.64/lib/libboost_unit_test_framework.so: undefined reference to std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_ostringstream()@GLIBCXX_3.4.21' /opt/apps/gcc7_1/boost/1.64/lib/libboost_unit_test_framework.so: undefined reference tostd::runtime_error::runtime_error(char const*)@GLIBCXX_3.4.21'
/opt/apps/gcc7_1/boost/1.64/lib/libboost_unit_test_framework.so: undefined reference to std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::basic_ostringstream(std::_Ios_Openmode)@GLIBCXX_3.4.21' /opt/apps/gcc7_1/boost/1.64/lib/libboost_system.so: undefined reference tostd::__cxx11::basic_string<char, std::char_traits, std::allocator >::~basic_string()@GLIBCXX_3.4.21'
/opt/apps/gcc7_1/boost/1.64/lib/libboost_unit_test_framework.so: undefined reference to std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::append(char const*)@GLIBCXX_3.4.21' /opt/apps/gcc7_1/boost/1.64/lib/libboost_unit_test_framework.so: undefined reference tostd::__cxx11::basic_ostringstream<char, std::char_traits, std::allocator >::~basic_ostringstream()@GLIBCXX_3.4.21'
/opt/apps/gcc7_1/boost/1.64/lib/libboost_unit_test_framework.so: undefined reference to VTT for std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21' /opt/apps/gcc7_1/boost/1.64/lib/libboost_system.so: undefined reference tooperator delete(void*, unsigned long)@CXXABI_1.3.9'
/opt/apps/gcc7_1/boost/1.64/lib/libboost_unit_test_framework.so: undefined reference to std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find(char const*, unsigned long, unsigned long) const@GLIBCXX_3.4.21' /opt/apps/gcc7_1/boost/1.64/lib/libboost_unit_test_framework.so: undefined reference tostd::__cxx11::basic_istringstream<char, std::char_traits, std::allocator >::basic_istringstream(std::__cxx11::basic_string<char, std::char_traits, std::allocator > const&, std::_Ios_Openmode)@GLIBCXX_3.4.21'
/opt/apps/gcc7_1/boost/1.64/lib/libboost_unit_test_framework.so: undefined reference to std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_stringstream()@GLIBCXX_3.4.21' /opt/apps/gcc7_1/boost/1.64/lib/libboost_unit_test_framework.so: undefined reference tostd::runtime_error::runtime_error(std::runtime_error const&)@GLIBCXX_3.4.21'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/test_OpmLog] Error 1
make[1]: *** [CMakeFiles/test_OpmLog.dir/all] Error 2
make: *** [all] Error 2

**Comment by atgeirr** [comment] 2018-03-02 10:24
Looks like a duplicate of #336, try the tip posted there, also a link was posted to a page where similar problems are discussed. Hope that helps, if not please update us.

Closing this issue as a duplicate, use #336 for further discussion.

**Closed by atgeirr** 2018-03-02 10:24 UTC
Labels: duplicate
