### ISSUE TITLE
MASTER: Parially Broken Command Line Parameters

### ISSUE THREAD

**Issue by OPMUSER** [OPM/opm-common#3168] opened 2022-10-05 04:58 UTC
OPMRUN generates the parameter file from the `--help` command parameter, so that the user can edit any of the supported parameters. This morning, this does not work because of unsupported parameters being listed when using `--help`.

![2022-10-05 12_54_37-Kubuntu 22 04 LTS OPM Development  Running  - Oracle VM VirtualBox _ 1](https://user-images.githubusercontent.com/17958927/193984433-e75fb0d1-2a05-4450-a65c-e1a0f785d333.png)

Be nice if somebody fixed this.

**Comment by blattms** [comment] 2022-10-11 19:20
Thanks for testing. I can confirm this.
I think the cause is that these variables are never queried in a default run of flow (and were before); maybe because certain if-else branches are never executed that previously were. I will need to double check this, though. Anyway this should be fixed for the release.

**Comment by blattms** [comment] 2022-10-11 19:38
I guess my assumption is right. I just cannot identify the change that resulted in this.
The parameters are defined in opm-models.
Many of the Vtk parameters are already hidden for flow. that might be  an option for these, too.

**Comment by atgeirr** [comment] 2022-10-14 07:28
Looking at this now. There are two different behaviours. If I give random non-existing parameters, such as `flow SPE1CASE2.DATA --a=b --c=d`, then flow terminates with
```
# [unused run-time specified parameters]
A="b"
C="d"
Aborting simulation due to unknown parameters. Please query "flow --help" for supported command line parameters.
```
However, if I instead use `flow SPE1CASE2.DATA --vtk-write-diffusion-coefficients=true` the deck is read before the exit!

(Also, I think the options should be hidden, that may or may not be a separate issue.)

**Comment by OPMUSER** [comment] 2022-10-14 07:40
```
# vtk-write-diffusion-coefficients=false
# vtk-write-effective-diffusion-coefficients=false
# vtk-write-tortuosities=false

```
Total of three command line problems.

**Comment by atgeirr** [comment] 2022-10-14 07:49
I have found the cause, will try to fix.

**Comment by OPMUSER** [comment] 2022-10-14 08:33
> (Also, I think the options should be hidden, that may or may not be a separate issue.)

@atgeirr Yes, I think they should be hidden as well.

**Comment by atgeirr** [comment] 2022-10-14 08:48
PRs created.

**Closed** 2022-10-14 09:28 UTC
