### ISSUE TITLE
Performance regression

### ISSUE THREAD

**Issue by alfbr** [OPM/opm-common#943] opened 2019-08-14 08:05 UTC
On August 7th or late 6th a regression occurred that causes output writing to take a large part of the simulation time. To reproduce, simply run the Norne model and observe that output writing time causes the total simulation time to almost double.

Looking at pull requests merged around that time, we have the following candidates:
https://github.com/OPM/opm-common/pull/925
https://github.com/OPM/opm-common/pull/924
https://github.com/OPM/opm-common/pull/913
https://github.com/OPM/opm-common/pull/900
https://github.com/OPM/opm-simulators/pull/1954
https://github.com/OPM/opm-simulators/pull/1945
https://github.com/OPM/opm-simulators/pull/1962

Please note that output writing to binary files is supposed to be off-loaded to an async thread through the tasklet mechanism.

**Comment by bska** [comment] 2019-08-14 08:20
I invite everyone to have a look at this. If it is not resolved by then I will analyse the issue when I am back in the office in one week, on Wednesday the 21st of August.

**Comment by joakim-hove** [comment] 2019-08-14 08:21
I will look on the opm-common cases during the day.

**Comment by joakim-hove** [comment] 2019-08-14 08:46
Regarding this:

> Please note that output writing to binary files is supposed to be off-loaded to an async thread through the tasklet mechanism.

Do you indicate that the problem is that the off-load mechanism has been sidelined in some way; or is this just a general background comment?

**Comment by alfbr** [comment] 2019-08-14 08:50
> Do you indicate that the problem is that the off-load mechanism has been sidelined in some way; or is this just a general background comment?

It could be. The binary files are certainly the largest files by a large margin. The threading is supposed to insulate the computational time from the disk writing time. Not jumping to conclusions though, simply noting that it is one of the possible suspects.

**Comment by GitPaean** [comment] 2019-08-14 08:56
Maybe we can create some revert PRs for testing purpose to find the related PRs first?

**Comment by joakim-hove** [comment] 2019-08-14 08:58
I would start with: OPM/opm-simulators#1962

**Comment by akva2** [comment] 2019-08-14 09:02
#1962 does not even affect the flow executable.

**Comment by akva2** [comment] 2019-08-14 09:31
while it's very hard to revert #900 (with downstream), just hopping in git history before / after that brings output time from 16 secs to 360 secs. so i'm certain it is the culprit.

**Comment by joakim-hove** [comment] 2019-08-14 09:35
Ok - thank you for the bisecting effort, I will look into it later today. Hopefully I will get a fix out today.

**Comment by joakim-hove** [comment] 2019-08-14 09:57
Just a preparatory question: Do we have a small timer utility class in the codebase?

**Comment by atgeirr** [comment] 2019-08-14 11:12
> Do we have a small timer utility class somewhere in the codebase?

Several...

I like the opm-grid/opm/grid/utility/StopWatch.hpp since I have used it for two decades (implementation a lot simpler now with c++ chrono). It is in opm-grid and not opm-common because it is important to some to build opm-grid without opm-common. If it was only up to me it should be in opm-common of course...

**Comment by joakim-hove** [comment] 2019-08-14 11:13
Well - some has left the building - time to move.

**Comment by atgeirr** [comment] 2019-08-14 12:04
I did not understand your comment, but the problem is evalSummaryState(). Investigating.

**Comment by joakim-hove** [comment] 2019-08-14 12:09
Ok - very good, I have not had the possibility to look into it yet, but I know that also @akva2 is looking.

**Comment by joakim-hove** [comment] 2019-08-14 12:10
If eval summaryState is the culprit I would look into the grouptree / GTNode stuff.

**Comment by atgeirr** [comment] 2019-08-14 12:11
It is indeed the grouptree. The call in Summary.cpp line 1435 takes almost half my runtime:
```
    const auto groupTree = schedule.groupTree(sim_step);
```

**Comment by joakim-hove** [comment] 2019-08-14 12:14
OK - beautiful; unless someone beats me to it I will look into that tonight.

**Comment by atgeirr** [comment] 2019-08-15 06:06
Closing as resolved.

**Closed by atgeirr** 2019-08-15 06:06 UTC
