### ISSUE TITLE
HAVE_OPM_COMMON - Failed

### ISSUE THREAD

**Issue by flikka** [OPM/opm-common#40] opened 2015-09-16 06:56 UTC
Hi! 

Currently all modules that have OPM-COMMON in their prereq fails the test. It is of course an irony, since the test is found in OPM-COMMON. It doesn't find itself. Many of us have that problem...

Anyway - should I dig into this, or is it blatantly obvious (me not being a cmake knowledgeable person)?

Since the prereq is not REQUIRED in most modules, things just continue smoothly. But some modules (opm-benchmarks, opm-polymer, opm-upscaling, opm-verteq) have opm-common as REQUIRED, and thus won't continue.

I guess one of these two alternatives apply:

A) This should work - you're doing something wrong (help appreciated)
B) This currently doesn't work / make sense, since we have no code/headers in the module (thus we should remove the REQUIRED on the modules having it as such?)

Thank you

**Comment by atgeirr** [comment] 2015-09-16 07:00
Some time ago it was mentioned that a library is needed for the Find... macros to successfully find an Opm module. If this still holds, that could be the reason, and a temporary solution would be to put an empty dummy function in opm-common.

**Comment by bska** [comment] 2015-09-16 07:36
> Some time ago it was mentioned that a library is needed for the Find... macros to successfully find an Opm module

That can't be it, at least not all of it.  As @andlaus [mentioned](https://github.com/OPM/opm-common/pull/35#discussion_r38972584), module opm-material does not have a library and is nevertheless found through the regular mechanisms.  Besides, for the longest time I used the following patch to `Findopm-upscaling.cmake` in order to build and run opm-benchmarks in a configuration targeting Dune 2.2.1.  The reason being that opm-upscaling does not create a library file in that configuration.
```diff
diff --git a/cmake/Modules/Findopm-upscaling.cmake b/cmake/Modules/Findopm-upscaling.cmake
index c802d8f..6fafc70 100644
--- a/cmake/Modules/Findopm-upscaling.cmake
+++ b/cmake/Modules/Findopm-upscaling.cmake
@@ -23,7 +23,8 @@ find_opm_package (
   "opm/upscaling/SinglePhaseUpscaler.hpp"
 
   # library to search for
-  "opmupscaling"
+  #"opmupscaling"
+  ""
 
   # defines to be added to compilations
   ""
```

**Comment by babrodtk** [comment] 2015-09-16 07:39
I think @akva2 mentioned that it does not have to produce a library, but it must have at least a header or cpp file to be "found". So perhaps adding a doxygen-friendly header file will enable the use of REQUIRED?

**Comment by bska** [comment] 2015-09-16 07:54
> [A module] must have at least a header or cpp file to be "found"

That makes sense.

> So perhaps adding a doxygen-friendly header file will enable the use of REQUIRED?

Could be.  At the very least this work-around warrants testing.

**Comment by flikka** [comment] 2015-09-16 08:16
Thanks - I will try this!

**Comment by akva2** [comment] 2015-09-16 09:30
i need to be able to reproduce the problem to fix it. i cannot. neither in sibling mode nor in install mode, it all just works without passing any additional options (or well, i had to fix ert in install mode).

quick hacky scripts;
http://paste.ubuntu.com/12425482/ for install mode
http://paste.ubuntu.com/12425543/ for sibling mode

both ran just fine here mins ago.

benchmarks is deprecated and won't be updated.

**Comment by flikka** [comment] 2015-09-16 09:34
Hmm. I'm using -DOPM_COMMON_ROOT=/path/to/opm-common

IS that not how it's supposed to be done?

**Comment by akva2** [comment] 2015-09-16 09:35
only if you want to force it. but that should not break anything, i will try doing that.

**Comment by akva2** [comment] 2015-09-16 09:35
precision precision. install or sibling ?

**Comment by flikka** [comment] 2015-09-16 10:09
Well, somethings not quite right then - because if I just clone opm-common and opm-parser, and do NOT add the -DOPM_COMMON_ROOT option, I get error messages when running cmake in Parser

```
CMake Warning at CMakeLists.txt:103 (find_package):
  By not providing "FindCXX11Features.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "CXX11Features", but CMake did not find one.

  Could not find a package configuration file provided by "CXX11Features"
  with any of the following names:

    CXX11FeaturesConfig.cmake
    cxx11features-config.cmake

```

Adding the OPM_COMMON_ROOT option "fixes" that, but FIND_OPM_COMMON fails (but not required for parser, so it continues).

**Comment by akva2** [comment] 2015-09-16 10:21
then where is your ERT from ? cause that will fail due to missing ert on my boxes; -- Could NOT find ERT (missing:  ERT_INCLUDE_DIR ERT_LIBRARY)

**Comment by akva2** [comment] 2015-09-16 10:25
also, i can indeed reproduce the issue. what i cannot yet explain is why it only triggers if you set the variable and works fine if you do not. it makes no sense, since a particular value is assigned to the variable if none is specified by user and that's the only difference in the code

**Comment by joakim-hove** [comment] 2015-09-16 10:32
> what i cannot yet explain is why it only triggers if you set the variable and works fine if you do not

Is this related to my rather length comment here: https://github.com/OPM/opm-common/pull/38

**Comment by akva2** [comment] 2015-09-16 10:38
well, somewhat yes. if you do not specify the OPM_COMMON_ROOT in your example, it will work just fine (it does sibling-search for opm-common as well..)

then weird thing is that IF you specify OPM_COMMON_ROOT, which should be perfectly okay, it fails due to executing the test with REQUIRED specified.

i cannot yet grasp why the test is executed in the former case and not in the latter.

**Comment by atgeirr** [comment] 2015-09-16 10:46
I have now tested this (sibling build) as well:
 - The ert prerequisite is installed to a central location and is found there.
 - I cloned opm-common and opm-parser to a new dir.
 - In a separate dir I create build dirs for opm-common and opm-parser.
 - In each, I do "cmake <src_dir>; make" (this should not do much for opm-common yet).

No problems encountered. I also removed the opm-common build dir, no change. I then also set OPM_COMMON_ROOT, no change (that I observed, i.e. it still worked).

**Comment by akva2** [comment] 2015-09-16 10:47
yeah, that will work. but opm-polymer will fail/work depending on whether you specify or not.

**Comment by akva2** [comment] 2015-09-16 10:48
you can pick up the weirdness already in opm-core though. if you specify, the test HAVE_OPM_COMMON is executed, if you don't it is not.

**Comment by akva2** [comment] 2015-09-16 11:27
okay, mystery resolved. i can explain it if you want, but now it makes sense.

there are two issues;

1) if OPM_COMMON_ROOT is specified, we supress the find_package call to look for an installed package. this was the key to why things was different. in particular, if this is executed, the opm_common-FOUND variable was defined. the existence of this variable had consequences further down the buildsystem. this can be fixed in one of several ways;
- change logic - never do sibling search for opm-common, rely on OPM_COMMON_ROOT
- keep current logic, but add unset() calls in CMakeLists.txt in all modules.

i tend to prefer the second. if we are to have sibling build support it should be automagic for opm-common as well.

2) the REQUIRED module is not found and thus the modules fails. this is not an issue as such (cmake is correct), and the module is actually required. but since it supplies no header files, it cannot be marked as found. the solution here is to workaround as we have done in other modules, i.e. suggestion B) from initial issue.

**Comment by joakim-hove** [comment] 2015-09-16 11:34
> if we are to have sibling build support it should be automagic for opm-common as well.

Standard comments about sibling build notwithstanding I agree with this. 

Will `-DCMAKE_PREFIX_PATH` work as well; i.e will the following work:

1. Checkout `opm-common` and `opm-parser` in two *non sibling* directories.
2. Configure `opm-common` with `-DCMAKE_INSTALL_PREFIX=/opm/install` and `make install`
3. Configure `opm-parser` with `-DCMAKE_PREFIX_PATH=/opm/install`

I.e. will `opm-parser` find `opm-common` - and in particular the build system, in step 3?

**Comment by atgeirr** [comment] 2015-09-16 11:34
> keep current logic, but add unset() calls in CMakeLists.txt in all modules.

I accept this as a better solution since it makes things easier for users (me included). However I do not understand why we need to unset the FOUND variable, is there a short explanation for this? I would assume naïvely that if the ROOT variable is set, then FOUND should be true as well, unless the ROOT points to a bogus place (and then we should fail).

When code is added to opm-common, how will that impact this?

**Comment by akva2** [comment] 2015-09-16 11:38
the problem is this snippet in opm-common; https://github.com/OPM/opm-common/blob/master/cmake/Modules/OpmFind.cmake#L141

yes, it will influence things once headers are added. we need that test to be executed cause it will be the code responsible for adding include paths and libraries. the "manual" stuff in the cmakelists is just for the buildsystem.

**Comment by akva2** [comment] 2015-09-16 11:38
@joakim-hove nothing changes with install mode - that is all living in downtown sanity city. it's just sibling builds which are affected.

**Comment by atgeirr** [comment] 2015-09-16 11:52
> the "manual" stuff in the cmakelists is just for the buildsystem.

So a problem is that OPM_COMMON_ROOT is *both* the location of a module, and the location of the build system, and they have slightly different needs?

**Comment by akva2** [comment] 2015-09-16 11:59
no, that's not the problem.

the problem is that there is code to suppress multiple calls to find_package() for a particular module,
plus a little egg and chicken problem.

if the user do not specify OPM_COMMON_ROOT, we do not know if he wants a sibling search or a system search for opm-common. currently it works like this: check for a system package and if that is found, use that, else look for a sibling package.

in the latter case this means we end up doing two calls to find_package(opm-common) - one to look for the system package (which fails), and then one to look for it as a dependency of other modules - which will look in sibling dirs. now the problem is that the second call was suppressed due to the code i linked, since opm-common_FOUND was defined (and 0) from the first call. thus, i need to unset this variable to make sure the second call is executed.

**Comment by joakim-hove** [comment] 2015-09-16 12:01
> @atgeirr: So a problem is that OPM_COMMON_ROOT is both the location of a module, and the location of the build system, and they have slightly different needs?

> @akva2: no, that's not the problem.

Well - I am starting to see that as a problem; hopefully I am wrong.

**Comment by akva2** [comment] 2015-09-16 12:10
what is the problem caused by it?

**Comment by joakim-hove** [comment] 2015-09-16 12:51
> what is the problem caused by it?

Well - this is purely a *feeling* - solely backed up by my grey beard. But:

1. As we see now - it does add to the overall complexity of an already quite complex build system.
2. In my opinion it is a question of separation of concerns - specially in the install target(s). Current opm-common is heading toward an unclean mix of code (where the most interesting for downstream modules is the compiled product) - and a set of build system files which should not be 'built'.

But - hopefully my feelings will prove to be complete bogus.

**Comment by andlaus** [comment] 2015-09-21 10:56
hm. that whole issue was caused by sibling builds again? did I ever mentioned that I consider them more of an obstacle than a help? ;)

>    In my opinion it is a question of separation of concerns - specially in the install target(s). Current opm-common is heading toward an unclean mix of code (where the most interesting for downstream modules is the compiled product) - and a set of build system files which should not be 'built'.
>
> But - hopefully my feelings will prove to be complete bogus.

the alternative would be to have a separate `opm-cmake` module (besides `opm-common`) in the dependency chain of every module. since there is a clear need for common infrastructural C++ code, the only alternative which I can immediately see is to merge everything into one big repo, but then things would get _really_ messy IMO. On that front I also don't think that we will have any issues with this if we stay strict with what goes into `opm-common` because there's not much of a problem with mixing build system and C++ code in any of the dune core modules as far as I'm aware.

**Comment by joakim-hove** [comment] 2015-09-30 14:37
To me it seems like a variety of this issue still persists. When configuring `opm-material/opm-core`:
```
-- Finding package opm-common using module mode
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.23") 
-- Performing Test HAVE_OPM_COMMON
-- Performing Test HAVE_OPM_COMMON - Failed
-- opm-common_DIR = opm-common_DIR-NOTFOUND
-- Could NOT find opm-common (missing:  HAVE_OPM_COMMON) 
```
However the `cmake` instance running out of `opm-core` has obviously found the `opm-common` module  - otherwise the build would have failed hard!?

**Comment by joakim-hove** [comment] 2015-09-30 14:42
> To me it seems like a variety of this issue still persists. 

Hmm - this was maybe because `opm-common` still had no targets which could be found? Sorry about the noise.

**Comment by flikka** [comment] 2015-09-30 15:26
> Hmm - this was maybe because opm-common still had no targets which could be found? Sorry about the noise
> 
I indeed believe that to be the case, yes.

- Kristian -

**Comment by atgeirr** [comment] 2015-10-09 15:06
Since now opm-common has targets that are found, and the find script has been made to use it, this problem is gone. Closing.

**Closed by atgeirr** 2015-10-09 15:06 UTC
Labels: bug
