### ISSUE TITLE
Linking error with  compareECL

### ISSUE THREAD

**Issue by sogoogos** [OPM/opm-common#769] opened 2019-05-12 10:20 UTC
I got the following linking error when compiling with `-DCMAKE_BUILD_TYPE=Release -DUSE_MPI=1`.
```
[ 50%] Linking CXX executable bin/compareECL
Undefined symbols for architecture x86_64:
  "void ECLFilesComparator::printValuesForCell<std::__1::__bit_const_reference<std::__1::vector<bool, std::__1::allocator<bool> > > >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, unsigned long, unsigned long, EGrid*, std::__1::__bit_const_reference<std::__1::vector<bool, std::__1::allocator<bool> > > const&, std::__1::__bit_const_reference<std::__1::vector<bool, std::__1::allocator<bool> > > const&) const", referenced from:
      void ECLRegressionTest::deviationsForNonFloatingPoints<std::__1::__bit_const_reference<std::__1::vector<bool, std::__1::allocator<bool> > > >(std::__1::__bit_const_reference<std::__1::vector<bool, std::__1::allocator<bool> > >, std::__1::__bit_const_reference<std::__1::vector<bool, std::__1::allocator<bool> > >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long, unsigned long) in libtestutil.a(EclRegressionTest.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/compareECL] Error 1
make[1]: *** [CMakeFiles/compareECL.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 50%] Building CXX object CMakeFiles/mocksim.dir/msim/src/msim.cpp.o
[ 50%] Linking CXX static library lib/libmocksim.a
[ 50%] Built target mocksim
make: *** [all] Error 2
```
I use clang version: 
```
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

Am I missing something to compile it?

**Comment by alfbr** [comment] 2019-05-12 12:59
MPI is not supported on Apple systems. It works on Debian, Red Hat/CentOS and Ubuntu (with bionic as exception).

**Comment by bska** [comment] 2019-05-12 13:26
> MPI is not supported on Apple systems.

That is true. However, this issue does not appear to be MPI related. Rather, the linker does not find the explicit specialization for `bool` of the member function
```C++
template <typename T>
void EclFilesComparator::printValuesForCell(const std::string& keyword,
                                            const std::string reference,
                                            size_t kw_size, size_t cell, EGrid *grid,
                                            const T& value1, const T& value2) const;
```
that is instantiated in https://github.com/OPM/opm-common/blob/294c8aa2f77a2b8f61f336513119d78afa5e554b/examples/test_util/EclFilesComparator.cpp#L88 This might be a compiler issue or it might be a build system issue. Without additional information&mdash;like the exact command line that we're executing&mdash;it will be hard to analyse this problem further.

**Comment by sogoogos** [comment] 2019-05-12 13:52
Thank you for the comments! 
This is what I exactly did in `opm-common` directory:
```
mkdir cmake-build
cd cmake-build
cmake -DCMAKE_INSTALL_PREFIX=/path/to/install/dir -DCMAKE_PREFIX_PATH=/path/to/install/dir -DCMAKE_BUILD_TYPE=Release -DUSE_MPI=1 ..
make -j 2 
```
I have built `dune-common`, `dune-istl`, `dune-geometry`, `dune-grid` (all version 2.6.0) and installed `libecl` (github master). 

I just got the same error without MPI (`-DUSE_MPI=0`). 

Please let me know if you need further information.

**Comment by bska** [comment] 2019-05-12 20:53
> This is what I exactly did in opm-common directory:

Right, that looks perfectly fine. Still, I'd like to go one step further to establish what compile/link commands that ultimately ends up generating. Would you mind running
```
$ cmake --build . --target compareECL -- VERBOSE=1
```
in your build directory?  That will tell us what the build system is trying to do when linking the `compareECL` executable and maybe provide some insight into the failing link step.

For the record, here's what I see on my laptop running Ubuntu Linux 16.04.2 LTS.
```
$ cmake --build . --target compareECL -- VERBOSE=1
...
[ 97%] Linking CXX executable bin/compareECL
/usr/bin/cmake -E cmake_link_script CMakeFiles/compareECL.dir/link.txt --verbose=1
/usr/bin/g++-5   -std=c++14 -pipe -pedantic -Wall -Wextra -Wcast-align -Wcast-qual -Wchar-subscripts -Wformat-nonliteral -Wmissing-declarations -Wpointer-arith -Wredundant-decls -Wundef -Wwrite-strings -fopenmp -pthread -ggdb3 -O0 -D_GLIBCXX_DEBUG=1 -D_GLIBCXX_DEBUG_PEDANTIC=1 -DDEBUG   CMakeFiles/compareECL.dir/examples/test_util/compareECL.cpp.o  -o bin/compareECL  -L/home/bska/work/opm/inst/boost/1.64.0/lib/c++11/debug -rdynamic lib/libtestutil.a lib/libopmcommon.a /home/bska/work/opm/inst/dbg/lib/libecl.so.2.4 -lm -ldl -pthread -lz /home/bska/work/opm/inst/boost/1.64.0/lib/c++11/debug/libboost_system-gcc54-mt-d-1_64.so /home/bska/work/opm/inst/boost/1.64.0/lib/c++11/debug/libboost_filesystem-gcc54-mt-d-1_64.so /home/bska/work/opm/inst/boost/1.64.0/lib/c++11/debug/libboost_regex-gcc54-mt-d-1_64.so -Wl,-rpath,/home/bska/work/opm/inst/boost/1.64.0/lib/c++11/debug:/home/bska/work/opm/inst/dbg/lib: 
```

On another note, if you have Perl installed there's an even more direct route to obtaining the link command. Running `perl -ane 'map{print "$_\n"}split' CMakeFiiles/compareECL.dir/link.txt` on the same system as above gets me the output below. It'd be really interesting to see the setup on your system.
```
/usr/bin/g++-5
-std=c++14
-pipe
-pedantic
-Wall
-Wextra
-Wcast-align
-Wcast-qual
-Wchar-subscripts
-Wformat-nonliteral
-Wmissing-declarations
-Wpointer-arith
-Wredundant-decls
-Wundef
-Wwrite-strings
-fopenmp
-pthread
-ggdb3
-O0
-D_GLIBCXX_DEBUG=1
-D_GLIBCXX_DEBUG_PEDANTIC=1
-DDEBUG
CMakeFiles/compareECL.dir/examples/test_util/compareECL.cpp.o
-o
bin/compareECL
-L/home/bska/work/opm/inst/boost/1.64.0/lib/c++11/debug
-rdynamic
lib/libtestutil.a
lib/libopmcommon.a
/home/bska/work/opm/inst/dbg/lib/libecl.so.2.4
-lm
-ldl
-pthread
-lz
/home/bska/work/opm/inst/boost/1.64.0/lib/c++11/debug/libboost_system-gcc54-mt-d-1_64.so
/home/bska/work/opm/inst/boost/1.64.0/lib/c++11/debug/libboost_filesystem-gcc54-mt-d-1_64.so
/home/bska/work/opm/inst/boost/1.64.0/lib/c++11/debug/libboost_regex-gcc54-mt-d-1_64.so
-Wl,-rpath,/home/bska/work/opm/inst/boost/1.64.0/lib/c++11/debug:/home/bska/work/opm/inst/dbg/lib:
```

**Comment by sogoogos** [comment] 2019-05-12 23:15
Here is what I got with `$ cmake --build . --target compareECL -- VERBOSE=1`:
```
Scanning dependencies of target compareECL
/Library/Developer/CommandLineTools/usr/bin/make -f CMakeFiles/compareECL.dir/build.make CMakeFiles/compareECL.dir/build
[ 97%] Building CXX object CMakeFiles/compareECL.dir/examples/test_util/compareECL.cpp.o
/Library/Developer/CommandLineTools/usr/bin/c++  -DHAVE_CONFIG_H=1 -I/Volumes/Transcend/rmine/OPM_master/opm-common/cmake-build -I/Volumes/Transcend/rmine/OPM_master/opm-common/external/cjson -I/Volumes/Transcend/rmine/OPM_master/opm-common/cmake-build/include -I/Volumes/Transcend/rmine/OPM_master/opm-common -I/usr/local/include -isystem /Volumes/Transcend/rmine/OPM_master/libecl/lib/include -isystem /Volumes/Transcend/rmine/OPM_master/libecl/cmake-build/lib/include  -std=c++14 -pipe -Wall -pthread -O3 -DNDEBUG -mtune=native -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk   -std=c++14 -o CMakeFiles/compareECL.dir/examples/test_util/compareECL.cpp.o -c /Volumes/Transcend/rmine/OPM_master/opm-common/examples/test_util/compareECL.cpp
[100%] Linking CXX executable bin/compareECL
/usr/local/Cellar/cmake/3.13.4/bin/cmake -E cmake_link_script CMakeFiles/compareECL.dir/link.txt --verbose=1
/Library/Developer/CommandLineTools/usr/bin/c++  -std=c++14 -pipe -Wall -pthread -O3 -DNDEBUG -mtune=native -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/compareECL.dir/examples/test_util/compareECL.cpp.o  -o bin/compareECL  -L/usr/local/lib -Wl,-rpath,/usr/local/lib lib/libtestutil.a lib/libopmcommon.a /Volumes/Transcend/rmine/OPM_master/libecl/cmake-build/lib/libecl.2.4.dylib -lm /usr/lib/libz.dylib /usr/local/lib/libboost_system-mt.dylib /usr/local/lib/libboost_filesystem-mt.dylib /usr/local/lib/libboost_regex-mt.dylib 
```

Perl gave me the following:
```
$ perl -ane 'map{print "$_\n"}split' CMakeFiles/compareECL.dir/link.txt
/Library/Developer/CommandLineTools/usr/bin/c++
-std=c++14
-pipe
-Wall
-pthread
-O3
-DNDEBUG
-mtune=native
-isysroot
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk
-Wl,-search_paths_first
-Wl,-headerpad_max_install_names
CMakeFiles/compareECL.dir/examples/test_util/compareECL.cpp.o
-o
bin/compareECL
-L/usr/local/lib
-Wl,-rpath,/usr/local/lib
lib/libtestutil.a
lib/libopmcommon.a
/Volumes/Transcend/rmine/OPM_master/libecl/cmake-build/lib/libecl.2.4.dylib
-lm
/usr/lib/libz.dylib
/usr/local/lib/libboost_system-mt.dylib
/usr/local/lib/libboost_filesystem-mt.dylib
/usr/local/lib/libboost_regex-mt.dylib
```

**Comment by bska** [comment] 2019-05-13 19:30
> Perl gave me the following:
> 
> ```
> $ perl -ane 'map{print "$_\n"}split' CMakeFiles/compareECL.dir/link.txt
> [...]
> -o
> bin/compareECL
> -L/usr/local/lib
> -Wl,-rpath,/usr/local/lib
> lib/libtestutil.a
> lib/libopmcommon.a
> [...]
> ```

That looks perfectly fine to me&mdash;the error must be elsewhere. Unfortunately, I don't have a Mac system so I'm not in a position to try to reproduce the symptom locally. Perhaps @atgeirr could lend a hand since he uses a Mac?

**Comment by atgeirr** [comment] 2019-05-14 06:36
I also have linking problems, will investigate.

**Comment by atgeirr** [comment] 2019-05-14 07:08
The error is caused by using std::vector<bool>. The `operator[] const` for it shall return a `const_reference` type, which according to https://en.cppreference.com/w/cpp/container/vector_bool should be a straightforward bool. However it looks like in libc++ (the standard library used with clang) this is a `__bit_const_reference` instead, this may or may not be a standard violation. It looks like it is done on purpose after all. So eventually we try to call printValuesForCell with such an object, and this is not explicitly instantiated (only bool, int, double and string is) so linking fails.

Simple solution: pass `T(t1[i])` rather than `t1[i]` when calling `deviationsForNonFloatingPoints`. I'll make a PR.

**Comment by bska** [comment] 2019-05-15 07:35
@sogoogos : We have a candidate solution in master now (from PR #772) and @atgeirr verifies that it works for him.  Would you mind trying the new master sources and report back if it works for you, possibly by closing this issue?

**Comment by sogoogos** [comment] 2019-05-15 12:45
@bska Thank you for fixing it! But sorry to say that I got another linking error:

```
[ 47%] Linking CXX executable bin/test_msim
Undefined symbols for architecture x86_64:
  "Opm::RestartValue::RestartValue(Opm::data::Solution, Opm::data::WellRates)", referenced from:
      Opm::msim::output(unsigned long, bool, double, Opm::data::Solution const&, Opm::data::WellRates const&, Opm::EclipseIO&) const in libmocksim.a(msim.cpp.o)
  "Opm::data::Solution::data(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      pressure(Opm::EclipseState const&, Opm::Schedule const&, Opm::data::Solution&, unsigned long, double) in test_msim.cpp.o
  "Opm::data::Solution::insert(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, Opm::UnitSystem::measure, std::__1::vector<double, std::__1::allocator<double> >, Opm::data::TargetType)", referenced from:
      pressure(Opm::EclipseState const&, Opm::Schedule const&, Opm::data::Solution&, unsigned long, double) in test_msim.cpp.o
  "Opm::EclipseIO::writeInitial(Opm::data::Solution, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<int, std::__1::allocator<int> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::vector<int, std::__1::allocator<int> > > > >, Opm::NNC const&)", referenced from:
      Opm::msim::run(Opm::Schedule&, Opm::EclipseIO&) in libmocksim.a(msim.cpp.o)
  "Opm::EclipseIO::writeTimeStep(int, bool, double, Opm::RestartValue, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, double, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, double> > > const&, std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<double, std::__1::allocator<double> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::vector<double, std::__1::allocator<double> > > > > const&, std::__1::map<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int>, double, std::__1::less<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int> >, std::__1::allocator<std::__1::pair<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int> const, double> > > const&, bool)", referenced from:
      Opm::msim::output(unsigned long, bool, double, Opm::data::Solution const&, Opm::data::WellRates const&, Opm::EclipseIO&) const in libmocksim.a(msim.cpp.o)
  "Opm::EclipseIO::EclipseIO(Opm::EclipseState const&, Opm::EclipseGrid, Opm::Schedule const&, Opm::SummaryConfig const&)", referenced from:
      RUN::test_method() in test_msim.cpp.o
  "Opm::EclipseIO::~EclipseIO()", referenced from:
      RUN::test_method() in test_msim.cpp.o
  "Opm::data::Solution::has(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const", referenced from:
      pressure(Opm::EclipseState const&, Opm::Schedule const&, Opm::data::Solution&, unsigned long, double) in test_msim.cpp.o
  "Opm::EclipseIO::summaryState() const", referenced from:
      Opm::msim::post_step(Opm::Schedule&, Opm::data::Solution&, Opm::data::WellRates&, unsigned long, Opm::EclipseIO&) const in libmocksim.a(msim.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by bska** [comment] 2019-05-15 13:27
Thanks for the update.  This is curious.  The undefined symbols, once we normalise them, are

  * [`Opm::RestartValue::RestartValue(Opm::data::Solution, Opm::data::WellRates)`](https://github.com/OPM/opm-common/blob/5f43a18050f8988dd445c932f004d3c8e6d6df08/src/opm/output/eclipse/RestartValue.cpp#L35)

  * [`Opm::data::Solution::data(std::string const&)`](https://github.com/OPM/opm-common/blob/5f43a18050f8988dd445c932f004d3c8e6d6df08/src/opm/output/data/Solution.cpp#L35)

  * [`Opm::data::Solution::insert(std::string, Opm::UnitSystem::measure, std::vector<double>, Opm::data::TargetType)`](https://github.com/OPM/opm-common/blob/5f43a18050f8988dd445c932f004d3c8e6d6df08/src/opm/output/data/Solution.cpp#L43-L46)

  * [`Opm::EclipseIO::writeInitial(Opm::data::Solution, std::map<std::string, std::vector<int>>, Opm::NNC const&)`](https://github.com/OPM/opm-common/blob/5f43a18050f8988dd445c932f004d3c8e6d6df08/src/opm/output/eclipse/EclipseIO.cpp#L471)

  * [`Opm::EclipseIO::writeTimeStep(int, bool, double, Opm::RestartValue, std::map<std::string, double> const&, std::map<std::string, std::vector<double>> const&, std::map<std::pair<std::string, int>, double> const&, bool)`](https://github.com/OPM/opm-common/blob/5f43a18050f8988dd445c932f004d3c8e6d6df08/src/opm/output/eclipse/EclipseIO.cpp#L490-L497)

  * [`Opm::EclipseIO::~EclipseIO()`](https://github.com/OPM/opm-common/blob/5f43a18050f8988dd445c932f004d3c8e6d6df08/src/opm/output/eclipse/EclipseIO.cpp#L614)

  * [`Opm::data::Solution::has(std::string const&) const`](https://github.com/OPM/opm-common/blob/5f43a18050f8988dd445c932f004d3c8e6d6df08/src/opm/output/data/Solution.cpp#L31)

  * [`Opm::EclipseIO::summaryState() const`](https://github.com/OPM/opm-common/blob/5f43a18050f8988dd445c932f004d3c8e6d6df08/src/opm/output/eclipse/EclipseIO.cpp#L609)

These are all symbols that are supposed to be defined in the main opmcommon library, so I think we have a build system issue.  Please verify that `lib/libmocksim.a` is at least as recent as `lib/libopmcommon.a`, and that `CMakeFiles/test_msim.dir/link.txt` has the following library sequence:
```
[...] lib/libmocksim.a lib/libopmcommon.a [...]
```

It is possible to configure opm-common without the mock simulator (`-DENABLE_MOCKSIM:Bool=FALSE` on the `cmake` command line when creating the build directory), but I'd rather get to the bottom of this than resort to workarounds.

**Comment by bska** [comment] 2019-06-19 16:44
@sogoogos : Do you still see these symptoms?

**Comment by bska** [comment] 2019-07-06 20:48
I'm going to close this issue now due to inactivity.  Please reopen if the issue recurs.

**Closed by bska** 2019-07-06 20:48 UTC
